version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keytide_user
      POSTGRES_PASSWORD: test_keytide
      POSTGRES_DB: keytide
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
